# Site settings
title: openHAB Foundation
email: info@openhabfoundation.org
description: 
baseurl: ""
url: "https://openhabfoundation.org"
twitter_username: openhabfoundation
github_username:  openhabfoundation

# Build settings
markdown: kramdown

# These override Jekyll defaults
permalink: /:year/:title

# These are new (in addition to Jekyll's elements above )
organization: openHAB Foundation e.V.
placeholderimagesbaseurl: 

# You can specify your own separator, of course. 
# Use {{ m.excerpt }} in your .md Files in blog/_posts or members/_posts
excerpt_separator: <!--more--> 

# Additional gems for sitemap generation
gems:
  - jekyll-sitemap  
